#!/bin/sh
#
# Copyright (C) 2011 Denis Roio <jaromil@dyne.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# wait the boot to complete

APPROOT=/apps/tor

sleep 15

touch /tmp/tor.log

USBROOT=`cat /tmp/appsRoot | grep tor | sed 's/tor//`
echo "Tor app running on USB $USBROOT" >> /tmp/tor.log
date >> /tmp/tor.log
echo "args: $@" >> /tmp/tor.log

export USBROOT
export APPROOT


# shall generate the config
if ! [ -r $USBROOT/tor.conf ]; then
    echo "config file not found" >> /tmp/tor.log
    echo "place tor.conf in your usb key" >> /tmp/tor.log
    exit 0
else
# source settings
    . $USBROOT/tor.conf
    echo "config file found in ${USBROOT}tor.conf" >> /tmp/tor.log
fi

mkdir -p $USBROOT/.tor

